services:
  db:
    image: postgres:9
    environment:
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
      POSTGRES_DB: axelor
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  tomcat:
    image: tomcat:8.5-jdk8
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./data:/root/data
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    command: catalina.sh jpda run
